name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes Cypress (modo headless)
        uses: cypress-io/github-action@v6

      - name: Gerar relatório Mochawesome
        run: |
          npx mochawesome-merge cypress/reports/.jsons/*.json > cypress/reports/report.json
          npx marge cypress/reports/report.json --reportDir cypress/reports/html

      - name: Fazer upload do relatório HTML como artefato
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/html/
